### ISSUE TITLE
Writing an object using the data mappers skips booleans

### ISSUE THREAD

**Issue by mgroeneweg** [shannah/cn1-mirah-json-macros#3]
I ran into an issue with the POJO mappers: they skip booleans when writing an object to a map or JSON.

Test project can be downloaded from here:
https://github.com/mgroeneweg/CrashTestDummies/blob/master/CodenameOne/MapperBooleanIssue/TestProject.zip

**Comment by shannah** [comment]
Thanks.
Note to self.  This line:
https://github.com/shannah/mirah-macro-utils/blob/b0d30ca938206e9b58dca892575a1512bd522ea7/src/ca/weblite/mirah/utils/TypeUtil.mirah#L231

and
https://github.com/shannah/mirah-macro-utils/blob/b0d30ca938206e9b58dca892575a1512bd522ea7/src/ca/weblite/mirah/utils/TypeUtil.mirah#L317

Will fix this today.

**Comment by shannah** [comment]
OK.  This is fixed in the new release 0.1.5
https://github.com/shannah/cn1-mirah-json-macros/releases/tag/0.1.5

You should only need to replace the -macros.jar not the cn1lib.

**Comment by mgroeneweg** [comment]
Steve,

Great! Thanks for the quick follow up

With regards,

Marcel
