### ISSUE TITLE
Using the lib in IntelliJ

### ISSUE THREAD

**Issue by jegesh** [shannah/cn1-mirah-json-macros#7]
I'm trying to utilize this library in a cn1 project I'm developing in IntelliJ. IntelliJ comes with support for mirah, but no matter how I build the project, the macro doesn't generate the wrapper classes.  I know I'm doing everything else right, because I tried it with a Netbeans project and it worked fine.  So I understand this is probably related to how mirah integrates into CodenameOne.  Are there any plans for an IntelliJ plugin?

**Comment by shannah** [comment]
This requires the specific Netbeans Mirah plugin listed.  It includes some special Codename One project support.  Unfortunately it is only for Netbeans.
